// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCekF29VJvdg1bxl_p1X0qnZzfNK9431sc',
    appId: '1:523746350716:web:a1333d36f9c3a541ad9bf9',
    messagingSenderId: '523746350716',
    projectId: 'visionintelligence-481d8',
    authDomain: 'visionintelligence-481d8.firebaseapp.com',
    storageBucket: 'visionintelligence-481d8.firebasestorage.app',
    measurementId: 'G-Y26ZSZ3LL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApCU_pI7wMZ2_QoDNeQzUhtnYfznBv7ng',
    appId: '1:523746350716:android:25b177093a6dc90fad9bf9',
    messagingSenderId: '523746350716',
    projectId: 'visionintelligence-481d8',
    storageBucket: 'visionintelligence-481d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjUfUcCY5WZ7iiCUWkm1GUKRQ_EWw7d-0',
    appId: '1:523746350716:ios:21143d120edaf496ad9bf9',
    messagingSenderId: '523746350716',
    projectId: 'visionintelligence-481d8',
    storageBucket: 'visionintelligence-481d8.firebasestorage.app',
    iosBundleId: 'com.example.visionIntelligence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjUfUcCY5WZ7iiCUWkm1GUKRQ_EWw7d-0',
    appId: '1:523746350716:ios:21143d120edaf496ad9bf9',
    messagingSenderId: '523746350716',
    projectId: 'visionintelligence-481d8',
    storageBucket: 'visionintelligence-481d8.firebasestorage.app',
    iosBundleId: 'com.example.visionIntelligence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCekF29VJvdg1bxl_p1X0qnZzfNK9431sc',
    appId: '1:523746350716:web:1be06c9b266b21d0ad9bf9',
    messagingSenderId: '523746350716',
    projectId: 'visionintelligence-481d8',
    authDomain: 'visionintelligence-481d8.firebaseapp.com',
    storageBucket: 'visionintelligence-481d8.firebasestorage.app',
    measurementId: 'G-GMPSS0MGHH',
  );
}
